name = "__APP_NAME__"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Configure these via `wrangler secret put` for production.
# [vars] is for non-secret defaults only.
[vars]
OBS_COLLECTOR_URL = "__COLLECTOR_URL__"
