CREATE TABLE IF NOT EXISTS ask_evidence_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id TEXT NOT NULL,
  analysis_id TEXT NOT NULL,
  asked_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ask_evidence_events_recent
  ON ask_evidence_events (project_id, asked_at DESC);

CREATE INDEX IF NOT EXISTS idx_ask_evidence_events_analysis
  ON ask_evidence_events (project_id, analysis_id, asked_at DESC);

ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS analysis_id TEXT;

CREATE INDEX IF NOT EXISTS idx_alert_rules_analysis
  ON alert_rules (project_id, analysis_id);
