name = "obs-demo-api"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[vars]
TELEMETRY_COLLECTOR_URL = "http://localhost:8790"
TELEMETRY_COLLECTOR_TOKEN = ""
USAGE_COLLECTOR_INGEST_TOKEN = ""
